name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t fastapi-app .

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 34.228.54.56  # Your EC2 instance IP
          username: ubuntu    # Your EC2 instance username
          key: secrets.SSH_PRIVATE_KEY  # Your SSH private key
          script: |
            cd /home/ubuntu/fastapi-book-project  # Replace with your project path
            git pull origin main
            docker-compose up -d --build